apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sbfspot.fullname" . }}-config
type: Opaque
data:
{{- range $path, $_ := .Files.Glob "config/*" }}
  {{ $path | trimPrefix "config/" }}: {{ tpl ($.Files.Get $path) $ | b64enc }}
{{- end }}