{{- if .Values.uploader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sbfspot.fullname" . }}-uploader
  labels:
    {{- include "sbfspot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: uploader
      {{- include "sbfspot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/scripts: {{ include (print $.Template.BasePath "/configmap-scripts.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/config-secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{ end }}
      labels:
        app.kubernetes.io/component: uploader
        {{- include "sbfspot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sbfspot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: uploader
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /scripts/start.sh
          env:
            - name: DB_STORAGE
              value: mysql
            - name: ENABLE_SBFSPOT
              value: "0"
            - name: ENABLE_SBFSPOT_UPLOAD
              value: "1"
            - name: TZ
              value: {{ .Values.timezone }}
          resources:
            {{- toYaml .Values.uploader.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/sbfspot
              name: config
            - mountPath: /scripts
              name: scripts
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "sbfspot.fullname" . }}-config
        - name: scripts
          configMap:
            name: {{ include "sbfspot.fullname" . }}-scripts
            defaultMode: 0550
{{- end }}